export const LAYOUT_OPTIONS= {
  maxRatio: 3/2,
  minRatio: 9/16,
  fixedRatio: false,
  scaleLastRow: true,
  alignItems: 'center',
  bigClass: "OT_big",
  bigPercentage: 0.8,
  minBigPercentage: 0,
  bigFixedRatio: false,
  bigScaleLastRow: true,
  bigAlignItems: 'center',
  smallAlignItems: 'center',
  maxWidth: Infinity,
  maxHeight: Infinity,
  smallMaxWidth: Infinity,
  smallMaxHeight: Infinity,
  bigMaxWidth: Infinity,
  bigMaxHeight: Infinity,
  bigMaxRatio: 3/2,
  bigMinRatio: 9/16,
  bigFirst: true,


  window: window,
  ignoreClass: 'OT_ignore',
  onLayout: null,
};
